### ISSUE TITLE
Ruby capstone day 0

### ISSUE THREAD

**Issue by lucascomamala** [lucascomamala/catalog-of-my-things#20]
https://github.com/lucascomamala/catalog-of-my-things/projects/1

3 person team:

- Team member 1: [Ashamal Zahara](https://github.com/ashmalzahra)
- Team member 2: [Balikuddembe Emmanuel](https://github.com/Balikuddembe)
- Team member 3: [Lucas Comamala](https://github.com/lucascomamala/)

**Comment by OyePriscilla** [comment]
Hi @lucascomamala, @Balikuddembe and @ashmalzahra 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Link to GitHub project added ✔️ 
Information about the number of people in their group ✔️ 
List of GitHub usernames assigned to team members ✔️ 
Tasks distributed in a fair way ✔️ 

## Required Changes ♻️

- [x] Please kindly assign this omitted task as it is applicable to all the members in the group. 👍 
<img width="540" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/234117039-5e54c08b-3e0c-451d-978e-03abe8622711.png">

- [ ] This group task is missing as well. 👇 
<img width="464" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/234117323-f18ea95e-77e1-489d-a95d-7490be4d661c.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucascomamala** [comment]
Added missing points to our Kanban board

**Comment by zieeco** [comment]
# status: APPROVED :green_circle: :100: 

Hi, @Team, 


<img height="230" src="https://media0.giphy.com/media/KZBEzE4uPX3K36hCeD/giphy-downsized-medium.gif"/>

Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡

- Created Kanban Board :heavy_check_mark: 
- All cards are assigned to a team member :heavy_check_mark:
- All project requirements for team members and group tasks have a corresponding card :heavy_check_mark:


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
